/**:
    ros__parameters:
      registration_method: "NDT"
      ndt_resolution: 5.0
      ndt_step_size: 0.5
      transform_epsilon: 0.01
      voxel_leaf_size: 1.0
      scan_max_range: 500.0
      scan_min_range: 5.0
      scan_period: 0.1
      use_pcd_map: true
      map_path: "/home/duanye/save_map/fx_00.pcd"
      set_initial_pose: true
      initial_pose_x: 0.0
      initial_pose_y: 0.0
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: 0.0
      initial_pose_qw: 0.0
      use_odom: false
      use_imu: false
      enable_debug: false
